"""
Go Gin code generator for ReForge V2 Universal Mapper.
"""
from typing import List, Tuple
from app.parser.universal_parser import UniversalProject, UniversalRoute, UniversalModel

GO_TYPE_MAP = {
    "String": "string", "Integer": "int64", "Float": "float64",
    "Boolean": "bool", "DateTime": "time.Time",
}

def generate_go_gin(project: UniversalProject, upgrades: List[str] = None) -> List[Tuple[str, str]]:
    upgrades = upgrades or []
    files = [
        _go_mod(project),
        _main_go(project),
        _models_go(project.models),
        _routes_go(project.routes, project.models),
        _database_go(),
    ]
    if "docker" in upgrades:
        files.append(_dockerfile())
    return files


def _go_type(t: str) -> str:
    return GO_TYPE_MAP.get(t, "string")


def _go_mod(project: UniversalProject) -> Tuple[str, str]:
    module_name = project.name.lower().replace(" ", "-")
    content = f"""module github.com/reforge/{module_name}

go 1.21

require (
    github.com/gin-gonic/gin v1.9.1
    gorm.io/gorm v1.25.7
    gorm.io/driver/sqlite v1.5.5
)
"""
    return "go.mod", content


def _main_go(project: UniversalProject) -> Tuple[str, str]:
    content = f'''// Generated by ReForge from {project.source_language}/{project.source_framework}
package main

import (
    "github.com/gin-gonic/gin"
    "gorm.io/driver/sqlite"
    "gorm.io/gorm"
    "log"
)

var DB *gorm.DB

func main() {{
    var err error
    DB, err = gorm.Open(sqlite.Open("app.db"), &gorm.Config{{}})
    if err != nil {{
        log.Fatal("Failed to connect to database:", err)
    }}

    // Auto-migrate models
    DB.AutoMigrate({", ".join(f"&{m.name}{{}}" for m in project.models) or "&Item{}"})

    r := gin.Default()

    // CORS
    r.Use(func(c *gin.Context) {{
        c.Header("Access-Control-Allow-Origin", "*")
        c.Header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, PATCH")
        c.Header("Access-Control-Allow-Headers", "Content-Type, Authorization")
        c.Next()
    }})

    r.GET("/health", func(c *gin.Context) {{
        c.JSON(200, gin.H{{"status": "UP", "service": "{project.name}"}})
    }})

    RegisterRoutes(r)

    r.Run(":8080")
}}
'''
    return "main.go", content


def _models_go(models: List[UniversalModel]) -> Tuple[str, str]:
    structs = ['package main\n\nimport "time"\n\n']
    for m in models:
        fields = ["    ID   uint   `json:\"id\" gorm:\"primaryKey\"`"]
        for f in m.fields:
            if f.name.lower() in ("id", "_id"):
                continue
            goname = f.name[0].upper() + f.name[1:]
            gotype = _go_type(f.type)
            tag = f'`json:"{f.name}" gorm:"column:{f.name}"`'
            fields.append(f"    {goname} {gotype} {tag}")
        fields_str = "\n".join(fields)
        structs.append(f'''type {m.name} struct {{
{fields_str}
}}

''')
    return "models.go", "".join(structs)


def _routes_go(routes: List[UniversalRoute], models: List[UniversalModel]) -> Tuple[str, str]:
    model_name = models[0].name if models else "Item"
    header = f'''package main

import (
    "github.com/gin-gonic/gin"
    "net/http"
    "strconv"
)

func RegisterRoutes(r *gin.Engine) {{
'''
    route_lines = []
    for r in routes:
        path = r.path.replace("{", ":").replace("}", "")
        verb = r.method.capitalize()
        fn = f"handle{verb}{abs(hash(r.path)) % 10000}"
        route_lines.append(f'    r.{verb}("{path}", {fn})')

    handlers = []
    for r in routes:
        fn = f"handle{r.method.capitalize()}{abs(hash(r.path)) % 10000}"
        if r.method == "GET" and not r.path_params:
            body = f"""var items []{model_name}
    DB.Find(&items)
    c.JSON(http.StatusOK, items)"""
        elif r.method == "GET":
            p0 = r.path_params[0] if r.path_params else "id"
            body = f"""id := c.Param("{p0}")
    var item {model_name}
    if err := DB.First(&item, id).Error; err != nil {{
        c.JSON(http.StatusNotFound, gin.H{{"error": "Not found"}})
        return
    }}
    c.JSON(http.StatusOK, item)"""
        elif r.method == "POST":
            body = f"""var item {model_name}
    if err := c.ShouldBindJSON(&item); err != nil {{
        c.JSON(http.StatusBadRequest, gin.H{{"error": err.Error()}})
        return
    }}
    DB.Create(&item)
    c.JSON(http.StatusCreated, item)"""
        elif r.method in ("PUT", "PATCH"):
            p0 = r.path_params[0] if r.path_params else "id"
            body = f"""id := c.Param("{p0}")
    var item {model_name}
    if err := DB.First(&item, id).Error; err != nil {{
        c.JSON(http.StatusNotFound, gin.H{{"error": "Not found"}})
        return
    }}
    if err := c.ShouldBindJSON(&item); err != nil {{
        c.JSON(http.StatusBadRequest, gin.H{{"error": err.Error()}})
        return
    }}
    DB.Save(&item)
    c.JSON(http.StatusOK, item)"""
        elif r.method == "DELETE":
            p0 = r.path_params[0] if r.path_params else "id"
            body = f"""id := c.Param("{p0}")
    DB.Delete(&{model_name}{{}}, id)
    c.Status(http.StatusNoContent)"""
        else:
            body = 'c.JSON(http.StatusOK, gin.H{})'

        handlers.append(f'''func {fn}(c *gin.Context) {{
    {body}
}}
''')

    closing = "\n".join(route_lines) + "\n}\n\n"
    return "routes.go", header + closing + "\n".join(handlers)


def _database_go() -> Tuple[str, str]:
    content = """// Database setup - generated by ReForge
// Switch to PostgreSQL by replacing the driver:
// import "gorm.io/driver/postgres"
// dsn := "host=localhost user=postgres password=password dbname=mydb port=5432"
// DB, err = gorm.Open(postgres.Open(dsn), &gorm.Config{})
package main
"""
    return "database.go", content


def _dockerfile() -> Tuple[str, str]:
    content = """FROM golang:1.21-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server .

FROM alpine:latest
WORKDIR /app
COPY --from=build /app/server .
EXPOSE 8080
CMD ["./server"]
"""
    return "Dockerfile", content
