"""
Java Spring Boot code generator for ReForge V2 Universal Mapper.
Consumes a UniversalProject and produces a complete Spring Boot Maven project.
"""
from pathlib import Path
from typing import List, Tuple
from app.parser.universal_parser import UniversalProject, UniversalRoute, UniversalModel, UniversalField

PACKAGE = "com.reforge.app"
PACKAGE_PATH = PACKAGE.replace(".", "/")

TYPE_MAP = {
    "String": "String",
    "Integer": "Long",
    "Float": "Double",
    "Boolean": "Boolean",
    "DateTime": "java.time.LocalDateTime",
    "List": "java.util.List<String>",
}

def generate_spring_boot(project: UniversalProject, upgrades: List[str] = None, target_dir: Path = None) -> List[Tuple[str, str]]:
    """Returns list of (relative_path, content) tuples for all generated files."""
    upgrades = upgrades or []
    files = []
    files.append(_pom_xml(project, upgrades))
    files.append(_application_properties())
    files.append(_main_application())
    for model in project.models:
        files.append(_entity(model))
        files.append(_repository(model))
    # Group routes by model
    model_names = [m.name for m in project.models]
    model_name = model_names[0] if model_names else "Item"
    if project.routes:
        files.append(_controller(project.routes, model_name, project))
    if "docker" in upgrades:
        files.append(_dockerfile())
        files.append(_docker_compose("redis" in upgrades))
    if "openapi" in upgrades:
        files.append(_openapi_config())
    if "redis" in upgrades:
        files.append(_redis_config())
    return files


def _java_type(t: str) -> str:
    return TYPE_MAP.get(t, "String")


def _pom_xml(project: UniversalProject, upgrades: List[str]) -> Tuple[str, str]:
    art_id = project.name.lower().replace(" ", "-")
    openapi_dep = ""
    if "openapi" in upgrades:
        openapi_dep = """
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.3.0</version>
        </dependency>"""
    redis_dep = ""
    if "redis" in upgrades:
        redis_dep = """
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>"""
    content = f"""<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.4</version>
        <relativePath/>
    </parent>
    <groupId>{PACKAGE}</groupId>
    <artifactId>{art_id}</artifactId>
    <version>1.0.0</version>
    <name>{project.name}</name>
    <description>Migrated from {project.source_language}/{project.source_framework} by ReForge</description>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>{openapi_dep}{redis_dep}
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
"""
    return "pom.xml", content


def _application_properties() -> Tuple[str, str]:
    content = """# Generated by ReForge - Spring Boot Configuration
server.port=8080
spring.application.name=reforge-migrated-app

# H2 In-Memory Database (ready to run, no setup needed)
spring.datasource.url=jdbc:h2:mem:reforgedb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
"""
    return "src/main/resources/application.properties", content


def _main_application() -> Tuple[str, str]:
    content = f"""package {PACKAGE};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {{
    public static void main(String[] args) {{
        SpringApplication.run(Application.class, args);
    }}
}}
"""
    return f"src/main/java/{PACKAGE_PATH}/Application.java", content


def _entity(model: UniversalModel) -> Tuple[str, str]:
    fields_code = ["    @Id\n    @GeneratedValue(strategy = GenerationType.IDENTITY)\n    private Long id;\n"]
    getset = ["""    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
"""]
    for f in model.fields:
        if f.name.lower() in ("id", "_id"):
            continue
        jtype = _java_type(f.type)
        null_str = "false" if f.required else "true"
        fields_code.append(f"    @Column(nullable = {null_str})\n    private {jtype} {f.name};\n")
        cap = f.name[0].upper() + f.name[1:]
        getset.append(f"""    public {jtype} get{cap}() {{ return {f.name}; }}
    public void set{cap}({jtype} {f.name}) {{ this.{f.name} = {f.name}; }}
""")

    content = f"""package {PACKAGE}.entity;

import jakarta.persistence.*;
import java.io.Serializable;

/**
 * Entity migrated from {model.file} by ReForge
 */
@Entity
@Table(name = "{model.table_name}")
public class {model.name} implements Serializable {{

{"".join(fields_code)}
    public {model.name}() {{}}

{"".join(getset)}
}}
"""
    return f"src/main/java/{PACKAGE_PATH}/entity/{model.name}.java", content


def _repository(model: UniversalModel) -> Tuple[str, str]:
    content = f"""package {PACKAGE}.repository;

import {PACKAGE}.entity.{model.name};
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface {model.name}Repository extends JpaRepository<{model.name}, Long> {{
}}
"""
    return f"src/main/java/{PACKAGE_PATH}/repository/{model.name}Repository.java", content


def _controller(routes: List[UniversalRoute], model_name: str, project: UniversalProject) -> Tuple[str, str]:
    method_annots = {"GET": "@GetMapping", "POST": "@PostMapping", "PUT": "@PutMapping",
                     "DELETE": "@DeleteMapping", "PATCH": "@PatchMapping"}

    # Find common base path
    paths = [r.path for r in routes]
    base_path = "/api"
    if paths:
        parts = paths[0].rstrip("/").split("/")
        if len(parts) >= 3:
            base_path = "/" + "/".join(parts[1:3]).split("{")[0].rstrip("/")

    methods_code = []
    for idx, r in enumerate(routes):
        annot = method_annots.get(r.method, "@GetMapping")
        # sub path relative to base
        sub = r.path
        if base_path != "/" and sub.startswith(base_path):
            sub = sub[len(base_path):] or ""

        args = []
        for p in r.path_params:
            args.append(f"@PathVariable Long {p}")
        if r.method in ("POST", "PUT", "PATCH"):
            args.append(f"@RequestBody {model_name} payload")
        args_str = ", ".join(args)
        sub_expr = f'("{sub}")' if sub else ""
        sc_annot = '@ResponseStatus(HttpStatus.CREATED)\n    ' if r.status_code == 201 else ""

        if r.method == "GET" and not r.path_params:
            body = f"return ResponseEntity.ok(repository.findAll());"
            ret = f"ResponseEntity<java.util.List<{model_name}>>"
            mname = "getAll"
        elif r.method == "GET":
            p0 = r.path_params[0] if r.path_params else "id"
            body = f"return repository.findById({p0}).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());"
            ret = f"ResponseEntity<{model_name}>"
            mname = "getById"
        elif r.method == "POST":
            body = f"{model_name} saved = repository.save(payload);\n        return ResponseEntity.status(HttpStatus.CREATED).body(saved);"
            ret = f"ResponseEntity<{model_name}>"
            mname = "create"
        elif r.method in ("PUT", "PATCH"):
            p0 = r.path_params[0] if r.path_params else "id"
            body = f"if (!repository.existsById({p0})) return ResponseEntity.notFound().build();\n        payload.setId({p0});\n        return ResponseEntity.ok(repository.save(payload));"
            ret = f"ResponseEntity<{model_name}>"
            mname = "update"
        elif r.method == "DELETE":
            p0 = r.path_params[0] if r.path_params else "id"
            body = f"if (!repository.existsById({p0})) return ResponseEntity.notFound().build();\n        repository.deleteById({p0});\n        return ResponseEntity.noContent().build();"
            ret = "ResponseEntity<Void>"
            mname = "delete"
        else:
            body = "return ResponseEntity.ok().build();"
            ret = "ResponseEntity<Object>"
            mname = f"handle{idx}"

        methods_code.append(f"""    {annot}{sub_expr}
    {sc_annot}public {ret} {mname}({args_str}) {{
        {body}
    }}
""")

    ctrl_name = model_name
    content = f"""package {PACKAGE}.controller;

import {PACKAGE}.entity.{model_name};
import {PACKAGE}.repository.{model_name}Repository;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.util.List;

/**
 * REST Controller migrated from {project.source_language}/{project.source_framework} by ReForge
 */
@RestController
@RequestMapping("{base_path}")
@CrossOrigin(origins = "*")
public class {ctrl_name}Controller {{

    private final {model_name}Repository repository;

    public {ctrl_name}Controller({model_name}Repository repository) {{
        this.repository = repository;
    }}

{"".join(methods_code)}
}}
"""
    return f"src/main/java/{PACKAGE_PATH}/controller/{ctrl_name}Controller.java", content


def _dockerfile() -> Tuple[str, str]:
    content = """# Multi-stage Dockerfile generated by ReForge
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
"""
    return "Dockerfile", content


def _docker_compose(include_redis: bool) -> Tuple[str, str]:
    redis_svc = ""
    redis_env = ""
    if include_redis:
        redis_svc = """
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped"""
        redis_env = "\n      - SPRING_REDIS_HOST=redis\n      - SPRING_REDIS_PORT=6379"
    content = f"""version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod{redis_env}
    restart: unless-stopped{redis_svc}
"""
    return "docker-compose.yml", content


def _openapi_config() -> Tuple[str, str]:
    content = f"""package {PACKAGE}.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class OpenApiConfig {{
    @Bean
    public OpenAPI customOpenAPI() {{
        return new OpenAPI()
            .info(new Info()
                .title("Migrated API")
                .description("Generated by ReForge from source codebase")
                .version("1.0.0"));
    }}
}}
"""
    return f"src/main/java/{PACKAGE_PATH}/config/OpenApiConfig.java", content


def _redis_config() -> Tuple[str, str]:
    content = f"""package {PACKAGE}.config;

import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Configuration;

@Configuration
@EnableCaching
public class RedisCacheConfig {{
}}
"""
    return f"src/main/java/{PACKAGE_PATH}/config/RedisCacheConfig.java", content
